@startuml Diagrama_CU
actor Inquilino
Inquilino -right-> (Crear usuario)
Inquilino -right-> (Modificar usuario)
Inquilino -right-> (Borrar usuario)
Inquilino -left-> (Consultar reserva)
Inquilino --> (Valorar alojamiento)
Inquilino -up-> (Buscar alojamiento)
Inquilino --> (Alquilar alojamiento)
Inquilino -up-> (Login)

(Consultar reserva) <.down. (Cancelar reserva) : <<extends>>
(Reservar alojamiento) .right.> (Buscar alojamiento) : <<extends>>
(Alquilar alojamiento) ..> (Registrar check-in) : <<includes>>
(Consultar reserva) <.. (Realizar pago) : <<extends>>
(Reservar alojamiento) ..>  (Consultar reserva) : <<includes>>
(Consultar reserva) <.. (Editar reserva) : <<extends>>
 

actor Propietario
Propietario --> (Registrar check-in)
Propietario --> (Publicar alojamiento)
Propietario --> (Registrar check-out)
Propietario --> (Cobrar)
Propietario --> (Registrar usuario)

actor Plataforma_de_Pago
Plataforma_de_Pago -up-> (Realizar pago)
Plataforma_de_Pago -right-> (Devolucion dinero)
Plataforma_de_Pago --> (Cobrar)

note right of (Propietario)
  Los casos de uso del
  inquilino tambien son
  del propietario. 
end note

note bottom of (Valorar alojamiento)
  La valoracion se hace
  luego del check-out.
end note

note right of (Login)
  Cualquier CU extiende de este.
end note



/'
    CONSULTAS:
    * ¿Como diagramamos los pagos parciales?
    * Propietario --> (Pago efectivo)
    * No se deberia poder realizar un pago
      sin antes alquilar un alojamiento
      (¿esto es a nivel D_CU o DC ?)
    * ¿ Devolucion dinero es CU ?
    * Devolucion dinero es CU como se relaciona
      con la Plataforma_de_Pago
'/
@enduml