@startuml Diagrama_secuencia_consultar_Alojamiento_busqueda

/' Flujo Busqueda '/
actor Inquilino
boundary PantallaBuscarAlojamientos
control GestorAlojamientos
entity Alojamiento

activate Inquilino
Inquilino -> PantallaBuscarAlojamientos: tomarOpcionBuscarAlojamientos()
activate PantallaBuscarAlojamientos
PantallaBuscarAlojamientos -> PantallaBuscarAlojamientos: habilitarPantalla()
deactivate PantallaBuscarAlojamientos

Inquilino -> PantallaBuscarAlojamientos: buscarAlojamiento(filtros)
activate PantallaBuscarAlojamientos
PantallaBuscarAlojamientos -> GestorAlojamientos: buscarAlojamientos(filtros)
activate GestorAlojamientos
GestorAlojamientos -> GestorAlojamientos: buscarAlojamientos(filtros)
loop array_size & false
    GestorAlojamientos -> Alojamiento: existeAlojamiento()
    activate Alojamiento
    Alojamiento -> GestorAlojamientos: false
    deactivate Alojamiento
end

GestorAlojamientos -> PantallaBuscarAlojamientos: mostrarAlojamiento(List<Alojamiento>)
deactivate GestorAlojamientos

Inquilino -> PantallaBuscarAlojamientos : tomarAlojamiento(Alojamiento)
PantallaBuscarAlojamientos -> PantallaBuscarAlojamientos : mostrarAlojamiento
deactivate PantallaBuscarAlojamientos


/' Flujo Reserva '/

control GestorReservas
entity Reserva
entity NuevaReserva

Inquilino -> GestorReservas : tomarOpcionReservar()
activate GestorReservas
loop array_size & false
    GestorReservas -> Reserva: disponibilidadAlojamiento()
    activate Reserva
    Reserva -> GestorReservas: true
    deactivate Reserva
end
GestorReservas -> NuevaReserva : nuevaReserva(datos reserva)
activate NuevaReserva
deactivate NuevaReserva
GestorReservas --> PantallaBuscarAlojamientos : mensajeConfirmacion()
activate PantallaBuscarAlojamientos
deactivate PantallaBuscarAlojamientos
deactivate GestorReservas
deactivate Inquilino


@enduml